# Generated by Django 3.2.2 on 2021-05-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Введите частый вопрос', max_length=200)),
                ('answer', models.TextField(help_text='Введите краткий и понятный ответ на вопрос', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название жанра (Например: Экшн, Шутер, Хоррор и т.п.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Пользователь')),
                ('steam_id', models.CharField(max_length=50, verbose_name='steam_id')),
                ('community_visibility_state', models.CharField(max_length=10, verbose_name='Видимость профиля steam')),
                ('profile_state', models.CharField(max_length=10, verbose_name='Имеется ли профиль сообщества steam')),
                ('persona_name', models.CharField(max_length=200, verbose_name='Отображаемое имя пользователя steam')),
                ('comment_permission', models.CharField(max_length=10, verbose_name='Можно ли оставлять публичные комментарии')),
                ('profile_url', models.CharField(max_length=200, verbose_name='Можно ли оставлять публичные комментарии')),
                ('avatar', models.CharField(max_length=400, verbose_name='Автар (маленький размер)')),
                ('avatar_medium', models.CharField(max_length=400, verbose_name='Автар (средний размер)')),
                ('avatar_full', models.CharField(max_length=400, verbose_name='Автар (полный размер)')),
                ('avatar_hash', models.CharField(max_length=256, verbose_name='Хэш сумма аватара')),
                ('last_logoff', models.CharField(max_length=256, verbose_name='Дата последнего онлайна (по юникс)')),
                ('persona_state', models.CharField(max_length=10, verbose_name='Текущий статус пользователя')),
                ('primary_clan_id', models.CharField(max_length=100, verbose_name='ID основного клана пользователя steam')),
                ('time_created', models.CharField(max_length=256, verbose_name='Дата регистрации аккаунта steam (по юникс)')),
                ('persona_state_flags', models.CharField(max_length=10, verbose_name='С чего пользователь онлайн и прочее')),
            ],
        ),
    ]
