# Generated by Django 3.2.2 on 2021-05-08 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20210508_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='time_registered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регистрации на Pay4Win'),
        ),
    ]
