# Generated by Django 3.2.2 on 2021-05-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_steamuser_time_last_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='time_last_logged_in',
        ),
    ]
