# Generated by Django 3.2.2 on 2021-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_alter_steamuser_time_last_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='time_last_logged_in',
            field=models.DateTimeField(null=True, verbose_name='Последняя дата и время входа на Pay4Win'),
        ),
    ]
